import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const bank183=JSON.parse(fs.readFileSync('data/v2-research/validation-bank-183-v1.0.0.json','utf8'));
const bank=JSON.parse(fs.readFileSync('data/v2-research/validation-bank-293-v2.0.0.json','utf8'));
const historicalV4=JSON.parse(fs.readFileSync('data/v2-research/validation-bank-292-engagement-v4.0.0.json','utf8'));
const activeBank=JSON.parse(fs.readFileSync('data/v2-research/validation-bank-292-expression-v5.0.0.json','utf8'));
test('OWNER attempt #1 bank remains frozen at 183 unique revisions',()=>{assert.equal(bank183.status,'OWNER_AUTHORIZED_IMMUTABLE_HUMAN_VALIDATION');assert.equal(bank183.question_count,183);assert.deepEqual(bank183.formats,{LIKERT:93,SINGLE_SELECT:90});assert.equal(new Set(bank183.questions.map(q=>q.question_revision_id)).size,183);assert.equal(crypto.createHash('sha256').update(JSON.stringify(bank183.questions)).digest('hex'),bank183.bank_hash);});
test('external-validation bank is a new immutable 293-question child',()=>{assert.equal(bank.parent_bank_version,bank183.bank_version);assert.equal(bank.parent_bank_hash,bank183.bank_hash);assert.equal(bank.question_count,293);assert.deepEqual(bank.formats,{LIKERT:143,SINGLE_SELECT:150});assert.equal(new Set(bank.questions.map(q=>q.question_revision_id)).size,293);assert.equal(crypto.createHash('sha256').update(JSON.stringify(bank.questions)).digest('hex'),bank.bank_hash);assert.deepEqual(bank.questions.slice(0,183),bank183.questions);});
test('single-select validation content has four mapped, human-readable choices',()=>{for(const q of bank.questions.filter(q=>q.format==='SINGLE_SELECT')){assert.equal(q.options.length,4,q.id);assert.deepEqual(new Set(q.options.map(o=>o.color)),new Set(['red','blue','yellow','green']));for(const o of q.options)assert.ok(o.label?.trim(),`${q.id}/${o.id}`);}});
test('OWNER-authorized Expression V5 is active while Engagement V4 remains immutable history',()=>{assert.equal(activeBank.status,'OWNER_AUTHORIZED_ACTIVE_VALIDATION');assert.equal(activeBank.question_count,292);assert.deepEqual(activeBank.formats,{LIKERT:143,SINGLE_SELECT:149});assert.equal(activeBank.questions.some(q=>q.id==='C03-S-06'),false);assert.equal(crypto.createHash('sha256').update(JSON.stringify(activeBank.questions)).digest('hex'),activeBank.bank_hash);assert.equal(historicalV4.bank_version,'viago-validation-bank-292-engagement-v4.0.0');assert.equal(historicalV4.bank_hash,'f445dd34268cd33f07330df639ff19bf511b61c03f35276268d2da06c1ea4325');});
test('validation migration is isolated and browser-denied',()=>{const sql=fs.readFileSync('supabase/migrations/20260831010000_viago_quiz_v2_human_validation.sql','utf8');for(const table of ['validation_participants','validation_attempts','validation_feedback'])assert.match(sql,new RegExp(`viago_quiz\\.${table}`));assert.match(sql,/Completed validation attempts are immutable/);assert.match(sql,/revoke all .* from public,anon,authenticated/);assert.doesNotMatch(sql,/alter table viago_quiz\.(questions|question_options|quiz_attempts)/);});
test('public participant entry retains attempt isolation while OWNER analytics stays protected',()=>{const route=fs.readFileSync('app/api/v2/validation/route.ts','utf8'),page=fs.readFileSync('app/v2/validation/page.tsx','utf8'),access=fs.readFileSync('lib/v2/validationAccess.ts','utf8'),admin=fs.readFileSync('app/v2/admin/validation/page.tsx','utf8');assert.doesNotMatch(page,/hasValidationAccess|hasAdminSession|redirect/);assert.match(route,/canAccessValidationAttempt/);assert.match(route,/bindValidationAttempt/);assert.match(access,/httpOnly:true/);assert.match(access,/BANK_VERSION/);assert.match(admin,/requireAdminSession/);});
test('cohort access is explicitly expiring, revocable, and not an admin session',()=>{const access=fs.readFileSync('lib/v2/validationAccess.ts','utf8'),admin=fs.readFileSync('lib/v2/adminAuth.ts','utf8');assert.match(access,/VIAGO_VALIDATION_COHORT_ENABLED/);assert.match(access,/VIAGO_VALIDATION_COHORT_EXPIRES_AT/);assert.match(access,/VIAGO_VALIDATION_COHORT_TOKEN_HASH/);assert.doesNotMatch(access,/VIAGO_ADMIN_PASSWORD/);assert.match(admin,/VIAGO_ADMIN_PASSWORD/);});
test('validation runtime is version-bound',()=>{const engine=fs.readFileSync('lib/v2/validation.ts','utf8');assert.match(engine,/viago-validation-bank-human-recognition-purge-v1\.0\.0/);assert.match(engine,/VIAGO_RETEST_NOVELTY_ASSEMBLER_V1/);assert.match(engine,/26;i\+\+/);assert.match(engine,/for\(let i=0;i<6;i\+\+\)/);assert.match(engine,/SCORING_VERSION/);assert.match(engine,/BANK_HASH/);assert.match(engine,/history_snapshot_hash/);});
test('293-bank simulation is reproducible and selects every admitted item',()=>{const result=JSON.parse(fs.readFileSync('data/v2-research/assembler-293-bank-simulation.json','utf8'));assert.equal(result.go_recommendation,'GO_FOR_OWNER_REVIEW_BEFORE_EXTERNAL_DISTRIBUTION');assert.ok(result.reproducibility.every(x=>x.identical));assert.equal(result.results[1].selection.zero_selected.length,0);assert.equal(result.scoring.maximum_per_color,128);});
test('research scoring preserves the approved equal 128-point ceiling',()=>{const route=fs.readFileSync('app/api/v2/validation/route.ts','utf8'),engine=fs.readFileSync('lib/v2/validation.ts','utf8'),ui=fs.readFileSync('components/v2/ValidationClient.tsx','utf8');assert.match(engine,/red:0,blue:0,yellow:0,green:0/);assert.match(route,/Number\(answer\)<0\|\|Number\(answer\)>4/);assert.match(ui,/value:i/);});

test('public validation setup is open while attempts remain cookie-isolated',()=>{const page=fs.readFileSync('app/v2/validation/page.tsx','utf8'),route=fs.readFileSync('app/api/v2/validation/route.ts','utf8');assert.doesNotMatch(page,/redirect|hasValidationAccess|hasAdminSession/);assert.match(route,/bindValidationAttempt\(inserted\.data\.id\)/);assert.match(route,/canAccessValidationAttempt\(attemptId\)/);assert.doesNotMatch(route,/action==='start'[\s\S]{0,250}hasValidationAccess/);});

test('tester entry uses a natural name and conditional prior-color questions',()=>{const ui=fs.readFileSync('components/v2/ValidationClient.tsx','utf8'),route=fs.readFileSync('app/api/v2/validation/route.ts','utf8'),access=fs.readFileSync('lib/v2/validationAccess.ts','utf8');assert.match(ui,/Your name/);assert.match(ui,/Have you taken the VIAGO personality test before\?/);assert.match(ui,/Begin Assessment/);assert.match(ui,/priorExperience==='YES'/);assert.doesNotMatch(ui,/Participant code|Private research mode|Human validation|non-production|immutable evidence|Begin private validation/);assert.match(route,/participant_name/);assert.match(route,/randomUUID/);assert.match(route,/bindValidationParticipant/);assert.match(access,/PARTICIPANT_COOKIE/);assert.match(access,/httpOnly:true/);});

test('question-level feedback accepts short notes without changing the frozen bank',()=>{const ui=fs.readFileSync('components/v2/ValidationClient.tsx','utf8'),route=fs.readFileSync('app/api/v2/validation/route.ts','utf8'),detail=fs.readFileSync('app/v2/admin/validation/[attemptId]/page.tsx','utf8'),migration=fs.readFileSync('supabase/migrations/20260901190000_viago_validation_item_notes.sql','utf8');assert.match(ui,/What seemed off\?/);assert.match(ui,/maxLength=\{250\}/);assert.match(ui,/action:'note'/);assert.match(route,/action==='note'/);assert.match(route,/note\.length>250/);assert.match(route,/Question is not in this manifest/);assert.match(migration,/add column if not exists item_notes jsonb/);assert.match(detail,/Tester feedback/);assert.match(detail,/itemNotes/);});
