'use client';

import { useState } from 'react';

export type CanonicalOption={id:string;question_id:string;label:string;label_es:string|null;sort_order:number;is_active:boolean;red:number;blue:number;yellow:number;green:number};
export type CanonicalQuestion={id:string;is_active:boolean;prompt:string;prompt_es:string|null;category:string|null;difficulty:number|null;qtype:string;primary_color:string|null;color:string|null;likert_color:string|null};
export type DraftRow={revision_id:string;canonical_question_id:string;prompt_en:string;prompt_es:string|null;category:string|null;construct:string|null;dimension:string|null;context:string|null;content_kind:string|null;review_classification:string|null;review_reason:string|null;review_status:string;created_at:string;status:string;notes:string|null;updated_at:string;options:{id:string;label_en:string;label_es:string|null}[]};
function makeForm(question:CanonicalQuestion|undefined,options:CanonicalOption[],draft:DraftRow|undefined){return {prompt_en:draft?.prompt_en??question?.prompt??'',prompt_es:draft?.prompt_es??question?.prompt_es??'',category:draft?.category??question?.category??'',construct:draft?.construct??'',dimension:draft?.dimension??'',context:draft?.context??'',content_kind:draft?.content_kind??(question?.qtype==='likert'?'LIKERT':'SCENARIO'),review_classification:draft?.review_classification??'',review_reason:draft?.review_reason??'',review_status:draft?.review_status??'NOT_REVIEWED',notes:draft?.notes??'',options:options.map(o=>{const d=draft?.options.find(x=>x.id===o.id);return{id:o.id,label_en:d?.label_en??o.label,label_es:d?.label_es??o.label_es??''}})}}

const CLASSIFICATIONS=['KEEP','LIGHT_REWRITE','FULL_REWRITE','RETIRE_CANDIDATE','DEFER'];
const KINDS=['SCENARIO','TRADEOFF','LIKERT'];
const STATUSES=['NOT_REVIEWED','IN_REVIEW','REVIEWED'];

export default function V2QuestionEditor({questions,options,revisions}:{questions:CanonicalQuestion[];options:CanonicalOption[];revisions:DraftRow[]}){
 const [query,setQuery]=useState(''); const [type,setType]=useState('all'); const [selectedId,setSelectedId]=useState(questions[0]?.id||'');
 const question=questions.find(q=>q.id===selectedId)||questions[0];
 const canonicalOptions=options.filter(o=>o.question_id===question?.id);
 const history=revisions.filter(r=>r.canonical_question_id===question?.id).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
 const draft=history.find(r=>r.status==='DRAFT');
 const initial=makeForm(question,canonicalOptions,draft);
 const [form,setForm]=useState(initial); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 function select(id:string){const nextQuestion=questions.find(q=>q.id===id);const nextOptions=options.filter(o=>o.question_id===id);const nextDraft=revisions.filter(r=>r.canonical_question_id===id).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).find(r=>r.status==='DRAFT');setSelectedId(id);setForm(makeForm(nextQuestion,nextOptions,nextDraft));setMessage('')}
 const filtered=questions.filter(q=>(type==='all'||q.qtype===type)&&(`${q.prompt} ${q.prompt_es??''} ${q.id}`.toLowerCase().includes(query.toLowerCase())));
 const validation=[!form.prompt_en.trim()?'English wording is required.':'',form.review_classification&&!form.review_reason.trim()?'Classification requires a reason.':'',question?.qtype==='single'&&form.options.some(o=>!o.label_en.trim())?'Every option needs English wording.':''].filter(Boolean);
 const changes=[['English',question?.prompt,form.prompt_en],['Spanish',question?.prompt_es??'',form.prompt_es],['Category',question?.category??'',form.category],...canonicalOptions.flatMap((o,i)=>[['Option EN '+(i+1),o.label,form.options[i]?.label_en],['Option ES '+(i+1),o.label_es??'',form.options[i]?.label_es]])].filter(([,a,b])=>a!==b);
 async function save(){setBusy(true);setMessage('');const response=await fetch('/api/v2/admin/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question_id:question.id,...form})});const body=await response.json().catch(()=>({}));setBusy(false);setMessage(response.ok?'Draft saved. Published content is unchanged.':body.error||'Unable to save draft.');if(response.ok) location.reload();}
 async function discard(){setBusy(true);const response=await fetch('/api/v2/admin/drafts',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({question_id:question.id})});setBusy(false);setMessage(response.ok?'Draft discarded; history preserved.':'Unable to discard draft.');if(response.ok) location.reload();}
 const field=(key:keyof typeof form,label:string)=><label className="block text-xs font-bold uppercase tracking-[.12em] text-white/35">{label}<input value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm font-normal normal-case tracking-normal text-white outline-none focus:border-violet-400/60"/></label>;
 return <div className="mt-8 grid gap-6 xl:grid-cols-[360px_1fr]">
  <aside className="v2-panel rounded-3xl p-4"><input aria-label="Search questions" placeholder="Search all 151 questions…" value={query} onChange={e=>setQuery(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-sm outline-none focus:border-violet-400/60"/><div className="mt-3 flex gap-2">{['all','likert','single'].map(x=><button key={x} onClick={()=>setType(x)} className={`rounded-full px-3 py-1.5 text-xs capitalize ${type===x?'bg-violet-500/25 text-white':'bg-white/[.04] text-white/40'}`}>{x}</button>)}</div><div className="mt-4 max-h-[72vh] space-y-2 overflow-y-auto">{filtered.map(q=><button key={q.id} onClick={()=>select(q.id)} className={`w-full rounded-xl border p-3 text-left ${q.id===question.id?'border-violet-400/40 bg-violet-400/[.09]':'border-white/[.06] bg-black/10'}`}><div className="flex justify-between text-[10px] uppercase tracking-wider text-white/30"><span>#{questions.indexOf(q)+1} · {q.qtype}</span><span>{revisions.some(r=>r.canonical_question_id===q.id&&r.status==='DRAFT')?'Draft':'Published'}</span></div><p className="mt-2 line-clamp-2 text-sm leading-5 text-white/65">{q.prompt}</p></button>)}</div></aside>
  {question&&<section className="space-y-6"><div className="v2-panel rounded-3xl p-6 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><p className="v2-eyebrow">Canonical ID</p><code className="mt-2 block text-xs text-white/45">{question.id}</code></div><div className="flex gap-2"><Badge>{question.is_active?'Active':'Inactive'}</Badge><Badge>{question.qtype}</Badge><Badge>{draft?'Draft open':'Published only'}</Badge></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Fact label="Color" value={question.likert_color||question.primary_color||question.color||'Mixed'}/><Fact label="Difficulty" value={String(question.difficulty??'—')}/><Fact label="Publication" value="Canonical published"/><Fact label="Draft publish" value="Fail-closed"/></div></div>
  <div className="v2-panel rounded-3xl p-6 sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-semibold">Draft editor</h2><p className="mt-2 text-sm text-white/40">Save writes only to revision tables. Runtime content remains untouched.</p></div><button disabled title="Publishing requires a separately authorized governed workflow" className="rounded-xl border border-white/8 px-4 py-2 text-sm text-white/25">Publish locked</button></div>
   <div className="mt-7 grid gap-5 lg:grid-cols-2">{field('prompt_en','English wording')}{field('prompt_es','Spanish wording')}{field('category','Category / context label')}{field('construct','Construct')}{field('dimension','Dimension')}{field('context','Governed context')}</div>
   <div className="mt-5 grid gap-5 sm:grid-cols-3"><Select label="Content format" value={form.content_kind} values={KINDS} onChange={v=>setForm({...form,content_kind:v})}/><Select label="Review classification" value={form.review_classification} values={['',...CLASSIFICATIONS]} onChange={v=>setForm({...form,review_classification:v})}/><Select label="Review status" value={form.review_status} values={STATUSES} onChange={v=>setForm({...form,review_status:v})}/></div>
   <div className="mt-5 grid gap-5 lg:grid-cols-2">{field('review_reason','Classification reason')}{field('notes','Review notes')}</div>
   {question.qtype==='single'&&<div className="mt-7 space-y-3"><h3 className="text-xs font-bold uppercase tracking-[.14em] text-white/35">Options · canonical order and scoring locked</h3>{canonicalOptions.map((o,i)=><div key={o.id} className="rounded-2xl border border-white/[.07] bg-black/15 p-4"><div className="grid gap-3 lg:grid-cols-2"><input value={form.options[i]?.label_en??''} onChange={e=>{const next=[...form.options];next[i]={...next[i],label_en:e.target.value};setForm({...form,options:next})}} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"/><input value={form.options[i]?.label_es??''} onChange={e=>{const next=[...form.options];next[i]={...next[i],label_es:e.target.value};setForm({...form,options:next})}} className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm"/></div><div className="mt-2 text-[10px] text-white/30">Order {o.sort_order} · R{o.red} B{o.blue} Y{o.yellow} G{o.green}</div></div>)}</div>}
   <div className="mt-7 rounded-2xl border border-white/[.07] bg-black/15 p-5"><h3 className="font-semibold">Validation & published-vs-draft diff</h3>{validation.length?<ul className="mt-3 list-disc pl-5 text-sm text-amber-200/70">{validation.map(v=><li key={v}>{v}</li>)}</ul>:<p className="mt-3 text-sm text-emerald-300/70">Draft validation passes. Publishing remains disabled.</p>}<div className="mt-4 space-y-2">{changes.length?changes.map(([label,a,b])=><div key={String(label)} className="rounded-xl bg-white/[.03] p-3 text-xs"><strong>{label}</strong><div className="mt-1 text-red-200/45 line-through">{a||'—'}</div><div className="mt-1 text-emerald-200/65">{b||'—'}</div></div>):<p className="text-sm text-white/35">No wording changes from published content.</p>}</div></div>
   <div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void save()} disabled={busy||validation.length>0} className="rounded-xl bg-violet-600 px-5 py-3 text-sm font-semibold disabled:opacity-40">Save Draft</button><button onClick={()=>setForm(initial)} disabled={busy} className="rounded-xl border border-white/10 px-5 py-3 text-sm text-white/55">Reset changes</button><button onClick={()=>void discard()} disabled={busy||!draft} className="rounded-xl border border-red-300/15 px-5 py-3 text-sm text-red-200/55 disabled:opacity-30">Discard Draft</button>{message&&<span className="self-center text-sm text-white/55">{message}</span>}</div>
  </div>
  <div className="grid gap-6 lg:grid-cols-2"><div className="v2-panel rounded-3xl p-6"><h2 className="text-lg font-semibold">Preview</h2><p className="mt-5 text-xl leading-8">{form.prompt_en||'Untitled question'}</p><p className="mt-3 text-sm text-white/45">{form.prompt_es||'Spanish preview unavailable'}</p></div><div className="v2-panel rounded-3xl p-6"><h2 className="text-lg font-semibold">Revision history</h2><div className="mt-4 space-y-2">{history.length?history.map(r=><div key={r.revision_id} className="rounded-xl border border-white/[.06] p-3 text-xs"><div className="flex justify-between"><strong>{r.status}</strong><span className="text-white/30">{formatUtc(r.updated_at)}</span></div><p className="mt-1 text-white/40">{r.review_classification||'Unclassified'} · {r.review_status}</p></div>):<p className="text-sm text-white/35">No revision history yet.</p>}</div></div></div>
 </section>}</div>;
}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full border border-white/10 bg-white/[.04] px-3 py-1 text-xs capitalize text-white/55">{children}</span>}
function Fact({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/[.06] bg-black/15 p-4"><div className="text-[10px] uppercase tracking-wider text-white/30">{label}</div><div className="mt-2 text-sm capitalize text-white/65">{value}</div></div>}
function Select({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(v:string)=>void}){return <label className="text-xs font-bold uppercase tracking-[.12em] text-white/35">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#111322] px-3 py-3 text-sm font-normal text-white"><option value="">Unclassified</option>{values.filter(Boolean).map(v=><option key={v}>{v}</option>)}</select></label>}
function formatUtc(value:string){return `${new Date(value).toISOString().replace('T',' ').slice(0,19)} UTC`}
