'use client';
import { useState } from 'react';
import Link from 'next/link';
import { V2Error, V2OfficialLogo } from '@/components/v2/V2Shell';

type Question={position:number;question_revision_id:string;format:'LIKERT'|'SINGLE_SELECT';prompt:string;options:{id:string;label:string}[]};
type Result={scores:Record<string,number>;primary:string;secondary:string;margin:number;ranking:string[]};
const flagOptions=[['confusing','Confusing'],['two_answers_true','Two answers feel true'],['no_answer_true','No answer feels true'],['obvious_best_answer','Obvious best answer'],['context_dependent','Context-dependent'],['repetitive','Repetitive'],['other','Other']] as const;
const likert=['Strongly disagree','Disagree','Neutral','Agree','Strongly agree'];
const colorHex:Record<string,string>={red:'#ff3d57',blue:'#35a8ff',yellow:'#ffc928',green:'#69d34d'};

export default function ValidationClient({retestInterval}:{retestInterval:string}){
 const [phase,setPhase]=useState<'setup'|'loading'|'quiz'|'result'|'done'>('setup');const [attemptId,setAttemptId]=useState('');const [attemptNumber,setAttemptNumber]=useState(0);const [questions,setQuestions]=useState<Question[]>([]);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Record<string,number|string>>({});const [flags,setFlags]=useState<Record<string,string[]>>({});const [result,setResult]=useState<Result|null>(null);const [error,setError]=useState('');
 async function call(body:Record<string,unknown>){const response=await fetch('/api/v2/validation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Validation request failed');return payload;}
 async function start(form:FormData){setPhase('loading');setError('');try{const started=await call({action:'start',participant_code:form.get('participant_code'),population:form.get('population'),known_primary:form.get('known_primary'),known_secondary:form.get('known_secondary')});const response=await fetch(`/api/v2/validation?attempt_id=${started.id}`,{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setAttemptId(started.id);setAttemptNumber(started.attempt_number);setQuestions(payload.manifest.questions);setPhase('quiz');}catch(c){setError(c instanceof Error?c.message:String(c));setPhase('setup');}}
 async function answer(value:number|string){const q=questions[index];setAnswers(v=>({...v,[q.question_revision_id]:value}));setError('');try{await call({action:'answer',attempt_id:attemptId,question_revision_id:q.question_revision_id,answer:value});}catch(c){setError(c instanceof Error?c.message:String(c));}}
 async function toggleFlag(flag:string){const q=questions[index],current=new Set(flags[q.question_revision_id]||[]),enabled=!current.has(flag);enabled?current.add(flag):current.delete(flag);setFlags(v=>({...v,[q.question_revision_id]:[...current]}));try{await call({action:'flag',attempt_id:attemptId,question_revision_id:q.question_revision_id,flag,enabled});}catch(c){setError(c instanceof Error?c.message:String(c));}}
 async function next(){if(index<49){setIndex(v=>v+1);return;}setPhase('loading');try{setResult(await call({action:'complete',attempt_id:attemptId}));setPhase('result');}catch(c){setError(c instanceof Error?c.message:String(c));setPhase('quiz');}}
 async function feedback(form:FormData){setPhase('loading');try{await call({action:'feedback',attempt_id:attemptId,result_feels_like_me:Number(form.get('result_feels_like_me')),primary_correct:form.get('primary_correct')==='yes',secondary_correct:form.get('secondary_correct')==='yes',repetitive:Number(form.get('repetitive')),natural:Number(form.get('natural')),notes:form.get('notes')});setPhase('done');}catch(c){setError(c instanceof Error?c.message:String(c));setPhase('result');}}
 const q=questions[index],selected=q?answers[q.question_revision_id]:undefined,currentFlags=q?flags[q.question_revision_id]||[]:[];
 return <main className="v2-page min-h-screen text-white"><div className="v2-ambient" aria-hidden/><div className="relative mx-auto min-h-screen w-full max-w-5xl px-4 pb-14 sm:px-7"><header className="flex min-h-24 items-center justify-between border-b border-white/[.07]"><V2OfficialLogo/><Link href="/v2/admin/validation" className="text-xs font-semibold uppercase tracking-[.15em] text-white/45">OWNER dashboard</Link></header>
 {phase==='setup'&&<section className="mx-auto max-w-2xl py-12"><p className="v2-eyebrow">Private research mode</p><h1 className="mt-3 text-4xl font-semibold">Human validation</h1><p className="mt-4 text-white/55">A non-production, 50-question research assessment. Answers and retests are stored as separate immutable evidence. Recommended retest interval: {retestInterval}.</p>{error&&<div className="mt-5"><V2Error message={error}/></div>}<form action={start} className="v2-panel mt-8 space-y-5 rounded-3xl p-7"><label className="block text-sm text-white/65">Participant code<input name="participant_code" required placeholder="Use a stable private code" className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3 text-white"/></label><label className="block text-sm text-white/65">Group<select name="population" className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1020] px-4 py-3"><option value="NEW">New to VIAGO</option><option value="EXPERIENCED">Experienced VIAGO user</option></select></label><div className="grid gap-4 sm:grid-cols-2"><ColorSelect name="known_primary" label="Known dominant (optional)"/><ColorSelect name="known_secondary" label="Known secondary (optional)"/></div><button className="v2-primary-button w-full">Begin private validation</button></form></section>}
 {phase==='loading'&&<div className="grid min-h-[70vh] place-items-center"><div className="text-center"><div className="mx-auto h-10 w-10 animate-spin rounded-full border-2 border-white/10 border-t-violet-400"/><p className="mt-4 text-white/50">Securing evidence…</p></div></div>}
 {phase==='quiz'&&q&&<section className="py-8"><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-violet-300">Validation attempt {attemptNumber}</p><p className="mt-1 text-sm text-white/45">Question {index+1} of 50</p></div><strong>{Math.round((index+1)/50*100)}%</strong></div><div className="mb-6 h-1.5 rounded-full bg-white/[.07]"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-blue-400" style={{width:`${(index+1)/50*100}%`}}/></div><article className="v2-panel rounded-3xl p-6 sm:p-9"><h1 className="mx-auto max-w-4xl text-center text-2xl font-semibold leading-tight sm:text-4xl">{q.prompt}</h1><div className={`mx-auto mt-8 grid max-w-3xl gap-3 ${q.format==='LIKERT'?'sm:grid-cols-5':''}`}>{(q.format==='LIKERT'?likert.map((label,i)=>({id:String(i+1),label,value:i+1})):q.options.map(o=>({...o,value:o.id}))).map((o,i)=><button key={o.id} onClick={()=>void answer(o.value)} className={`min-h-16 rounded-2xl border px-4 py-3 text-left ${selected===o.value?'border-violet-300 bg-violet-500/20':'border-white/10 bg-white/[.035] text-white/75 hover:border-white/25'} ${q.format==='LIKERT'?'sm:min-h-28 sm:text-center':''}`}><span className="mb-2 block text-xs font-black text-white/35">{q.format==='LIKERT'?i+1:String.fromCharCode(65+i)}</span>{o.label}</button>)}</div><details className="mx-auto mt-7 max-w-3xl rounded-2xl border border-white/[.08] bg-black/15 p-4"><summary className="cursor-pointer text-sm text-white/45">Flag this item (optional)</summary><div className="mt-4 flex flex-wrap gap-2">{flagOptions.map(([id,label])=><button key={id} onClick={()=>void toggleFlag(id)} className={`rounded-full border px-3 py-2 text-xs ${currentFlags.includes(id)?'border-amber-300/50 bg-amber-300/10 text-amber-100':'border-white/10 text-white/45'}`}>{label}</button>)}</div></details>{error&&<div className="mx-auto mt-5 max-w-3xl"><V2Error message={error}/></div>}<div className="mx-auto mt-7 flex max-w-3xl justify-between"><button disabled={index===0} onClick={()=>setIndex(v=>Math.max(0,v-1))} className="rounded-xl border border-white/10 px-5 py-3 disabled:opacity-30">← Back</button><button disabled={selected===undefined} onClick={()=>void next()} className="v2-primary-button">{index===49?'Calculate result':'Next →'}</button></div></article></section>}
 {phase==='result'&&result&&<section className="mx-auto max-w-3xl py-10"><p className="v2-eyebrow">Research result</p><h1 className="mt-3 text-4xl font-semibold capitalize">{result.primary} + {result.secondary}</h1><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(result.scores).map(([color,score])=><div key={color} className="v2-panel rounded-2xl p-4"><span className="capitalize" style={{color:colorHex[color]}}>{color}</span><strong className="mt-2 block text-3xl">{score}</strong></div>)}</div><form action={feedback} className="v2-panel mt-7 space-y-6 rounded-3xl p-7"><Scale name="result_feels_like_me" label="This result feels like me"/><YesNo name="primary_correct" label="The primary color feels correct"/><YesNo name="secondary_correct" label="The secondary color feels correct"/><Scale name="repetitive" label="The assessment felt repetitive"/><Scale name="natural" label="The questions felt natural"/><label className="block text-sm text-white/65">Optional notes<textarea name="notes" rows={4} className="mt-2 w-full rounded-xl border border-white/10 bg-black/30 p-3"/></label>{error&&<V2Error message={error}/>}<button className="v2-primary-button w-full">Submit feedback</button></form></section>}
 {phase==='done'&&<section className="mx-auto max-w-xl py-20 text-center"><h1 className="text-4xl font-semibold">Evidence saved.</h1><p className="mt-4 text-white/50">This attempt is now immutable. A future retest will create a new attempt and never overwrite this one.</p><Link href="/v2/admin/validation" className="v2-primary-button mt-8">Open OWNER dashboard</Link></section>}
 </div></main>;
}
function ColorSelect({name,label}:{name:string;label:string}){return <label className="block text-sm text-white/65">{label}<select name={name} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0b1020] px-4 py-3"><option value="">Unknown / not collected</option>{['red','blue','yellow','green'].map(c=><option key={c} value={c}>{c[0].toUpperCase()+c.slice(1)}</option>)}</select></label>}
function Scale({name,label}:{name:string;label:string}){return <fieldset><legend className="text-sm text-white/65">{label}</legend><div className="mt-2 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><label key={n} className="rounded-xl border border-white/10 p-3 text-center"><input type="radio" name={name} value={n} required className="mr-1"/>{n}</label>)}</div></fieldset>}
function YesNo({name,label}:{name:string;label:string}){return <fieldset><legend className="text-sm text-white/65">{label}</legend><div className="mt-2 flex gap-3">{['yes','no'].map(v=><label key={v} className="rounded-xl border border-white/10 px-5 py-3 capitalize"><input type="radio" name={name} value={v} required className="mr-2"/>{v}</label>)}</div></fieldset>}
